name: Send a test message

on:
  workflow_dispatch:
  
jobs:
  notify:
    name: Send Slack message 
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    os:
    #      - self-hosted-ubuntu-2004
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v2
      - id: success
        name: Send success message
        uses: asarco/slack_notify@v1.1.2
        #uses: ./
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_ICON_URL: 'https://github.githubassets.com/images/modules/logos_page/Octocat.png'
          SLACK_USERNAME: 'GitHub'
          SLACK_GITHUB_USER_PAIRS: |- 
            --asarco,U01CXS1NVDG
            --paulfairless,UMVKJNY64
            --noe-caratini,U01966NRYTG
            --martarey-benito,U01A7JL0Q5R
            --kevinmcrofts,U01NW807C66
          TITLE: ':tada: Congratulations ${{ github.actor }} :tada:'
          USE_MARKDOWN: true,
          BODY: "Your recent action _*${{ github.workflow }}*_ has been built succesfully! \n>This is *markdown* :partyparrot:"
          COLOR: '#FF0000'    
